system('git config --global user.email "forhad_isrt@outlook.com"')
system('git config --global user.name "forhad-ds"')
system("git pull")
system("git merge")
system("git add Image/CMS.png")
system(glue::glue('git commit -m " updated {updated_date}"'))
system("git push -u origin main")
